/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void bzero(void *s, size_t n);
int strcmp(const char *s1, const char *s2);
int __cdecl get_expr(char *expr, int size);
_DWORD *__cdecl eval(_DWORD *buf, char op);
_DWORD *__cdecl init_pool(_DWORD *);
int __cdecl parse_expr(char *expr, _DWORD *buf);
unsigned int calc();
_DWORD __cdecl atoi(_DWORD); // weak
int printf(const char *a1, ...);
_DWORD __cdecl fflush(_DWORD); // weak
_DWORD __cdecl puts(_DWORD); // weak
_DWORD __cdecl malloc(_DWORD); // weak
_DWORD __cdecl memcpy(_DWORD, _DWORD, _DWORD); // weak
_DWORD __cdecl vfprintf(_DWORD, _DWORD, _DWORD); // weak

//-------------------------------------------------------------------------
// Data declarations

void *stdout = &IO_2_1_stdout_; // weak


//----- (08049379) --------------------------------------------------------
unsigned int calc()
{
  int buf[101]; // [esp+18h] [ebp-5A0h] BYREF
  char expr[1024]; // [esp+1ACh] [ebp-40Ch] BYREF
  unsigned int v3; // [esp+5ACh] [ebp-Ch]

  v3 = __readgsdword(0x14u);
  while ( 1 )
  {
    bzero(expr, 0x400u);
    if ( !get_expr(expr, 1024) )
      break;
    init_pool(buf);
    if ( parse_expr(expr, buf) )
    {
      printf("%d\n", buf[buf[0]]);
      fflush(stdout);
    }
  }
  return __readgsdword(0x14u) ^ v3;
}
// 8050280: using guessed type _DWORD __cdecl fflush(_DWORD);
// 80EC4C0: using guessed type void *stdout;

// nfuncs=1106 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
