/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void bzero(void *s, size_t n);
int strcmp(const char *s1, const char *s2);
int __cdecl get_expr(char *expr, int size);
_DWORD *__cdecl eval(_DWORD *buf, char op);
_DWORD *__cdecl init_pool(_DWORD *);
int __cdecl parse_expr(char *expr, _DWORD *buf);
unsigned int calc();
_DWORD __cdecl atoi(_DWORD); // weak
int printf(const char *a1, ...);
_DWORD __cdecl fflush(_DWORD); // weak
_DWORD __cdecl puts(_DWORD); // weak
_DWORD __cdecl malloc(_DWORD); // weak
_DWORD __cdecl memcpy(_DWORD, _DWORD, _DWORD); // weak
_DWORD __cdecl vfprintf(_DWORD, _DWORD, _DWORD); // weak

//-------------------------------------------------------------------------
// Data declarations

void *stdout = &IO_2_1_stdout_; // weak


//----- (0804902A) --------------------------------------------------------
int __cdecl parse_expr(char *expr, _DWORD *buf)
{
  int v3; // eax
  char *operand_begin; // [esp+20h] [ebp-88h]
  int i; // [esp+24h] [ebp-84h]
  int v6; // [esp+28h] [ebp-80h]
  char *operand_size; // [esp+2Ch] [ebp-7Ch]
  char *operand_str; // [esp+30h] [ebp-78h]
  int operand; // [esp+34h] [ebp-74h]
  char s[100]; // [esp+38h] [ebp-70h] BYREF
  unsigned int v11; // [esp+9Ch] [ebp-Ch]

  v11 = __readgsdword(0x14u);
  operand_begin = expr;
  v6 = 0;
  bzero(s, 100u);
  for ( i = 0; ; ++i )
  {
    if ( expr[i] - (unsigned int)'0' > 9 )      // operator
    {
      operand_size = (char *)(&expr[i] - operand_begin);
      operand_str = (char *)malloc(operand_size + 1);
      memcpy(operand_str, operand_begin, operand_size);
      operand_str[(_DWORD)operand_size] = 0;
      if ( !strcmp(operand_str, "0") )
      {
        puts("prevent division by zero");
        fflush(stdout);
        return 0;
      }
      operand = atoi(operand_str);
      if ( operand > 0 )
      {
        v3 = (*buf)++;
        buf[v3 + 1] = operand;
      }
      if ( expr[i] && expr[i + 1] - (unsigned int)'0' > 9 )
      {
        puts("expression error!");
        fflush(stdout);
        return 0;
      }
      operand_begin = &expr[i + 1];
      if ( s[v6] )
      {
        switch ( expr[i] )
        {
          case '%':
          case '*':
          case '/':
            if ( s[v6] != '+' && s[v6] != '-' )
              goto LABEL_14;
            s[++v6] = expr[i];
            break;
          case '+':
          case '-':
LABEL_14:
            eval(buf, s[v6]);
            s[v6] = expr[i];
            break;
          default:
            eval(buf, s[v6--]);
            break;
        }
      }
      else
      {
        s[v6] = expr[i];
      }
      if ( !expr[i] )
        break;
    }
  }
  while ( v6 >= 0 )
    eval(buf, s[v6--]);
  return 1;
}
// 804E570: using guessed type _DWORD __cdecl atoi(_DWORD);
// 8050280: using guessed type _DWORD __cdecl fflush(_DWORD);
// 80504C0: using guessed type _DWORD __cdecl puts(_DWORD);
// 8059F80: using guessed type _DWORD __cdecl malloc(_DWORD);
// 805D680: using guessed type _DWORD __cdecl memcpy(_DWORD, _DWORD, _DWORD);
// 80EC4C0: using guessed type void *stdout;
// 804902A: using guessed type char s[100];

// nfuncs=1106 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
