/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_9D0();
// void free(void *ptr);
// int strncmp(const char *s1, const char *s2, size_t n);
// void __noreturn _exit(int status);
// __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int puts(const char *s);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// void *calloc(size_t nmemb, size_t size);
// int strcmp(const char *s1, const char *s2);
// char *strtok(char *s, const char *delim);
// char *strdup(const char *s);
// int rand(void);
// int __fastcall _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_B40();
__int64 sub_B80(void); // weak
void *sub_BD0();
__int64 sub_C10();
void __noreturn handler();
__int64 read_long();
void __fastcall read_input(char *a1, unsigned int a2);
int Menu();
int BountyMenu();
User *Register();
unsigned __int64 Login();
unsigned __int64 AddProduct();
VulnType *__fastcall AllocateType(const char *type_name, int price);
__int64 __fastcall FreeType(const char *name);
void AddVulnType();
int ShowTypes();
unsigned __int64 RemoveVulnType();
int ShowProduct();
int ShowBugDetail();
Product *__fastcall AddReportToProduct(Product *a1, BugReport *a2);
Product *__fastcall RemoveBugFromProduct(Product *a1, BugReport *a2);
void SubmitReport();
int DeleteReport();
unsigned __int64 ModifyReport();
int EvalVuln();
unsigned __int64 UserInfo();
void RemoveUser();
void ChangePassword();
void ChangeContact();
__int64 Bounty();
__int64 setup();
void __fastcall __noreturn main(const char *a1, char **a2, char **a3);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void fini(void); // idb
void term_proc();
// void free(void *ptr);
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// void *calloc(size_t nmemb, size_t size);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

const char byte_319F = '\xE2'; // idb
const char byte_3260 = '\xE2'; // idb
__int64 (__fastcall *funcs_2DD9)() = &sub_C10; // weak
__int64 (__fastcall *off_203D38)() = &sub_BD0; // weak
void *off_204008 = &off_204008; // idb
_UNKNOWN unk_204010; // weak
char byte_204048; // weak
char isLogginIn; // weak
User *user;
User *user_head;
User *admin;
Product *Products[8];
VulnType *VulnTypes[8];


//----- (00000000000009B0) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 2041C8: using guessed type __int64 _gmon_start__(void);

//----- (00000000000009D0) ----------------------------------------------------
void sub_9D0()
{
  JUMPOUT(0LL);
}
// 9D6: control flows out of bounds to 0

//----- (0000000000000B10) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, (void (*)(void))init, fini, a3, &v5);
  __halt();
}
// B16: positive sp value 8 has been found
// B1D: variable 'v3' is possibly undefined

//----- (0000000000000B40) ----------------------------------------------------
void *sub_B40()
{
  return &unk_204010;
}

//----- (0000000000000B80) ----------------------------------------------------
__int64 sub_B80()
{
  return 0LL;
}
// B80: using guessed type __int64 sub_B80();

//----- (0000000000000BD0) ----------------------------------------------------
void *sub_BD0()
{
  void *result; // rax

  if ( !byte_204048 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_204008);
    result = sub_B40();
    byte_204048 = 1;
  }
  return result;
}
// 204048: using guessed type char byte_204048;

//----- (0000000000000C10) ----------------------------------------------------
__int64 sub_C10()
{
  return sub_B80();
}
// B80: using guessed type __int64 sub_B80(void);

//----- (0000000000000C1A) ----------------------------------------------------
void __noreturn handler()
{
  puts("Timeout");
  _exit(1);
}

//----- (0000000000000C3B) ----------------------------------------------------
__int64 sub_C3B()
{
  char nptr[40]; // [rsp+10h] [rbp-30h] BYREF
  unsigned __int64 v2; // [rsp+38h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  __read_chk(0LL, nptr, 32LL, 32LL);
  return atoll(nptr);
}
// A10: using guessed type __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000C9C) ----------------------------------------------------
void __fastcall read_input(char *a1, unsigned int a2)
{
  int chk; // [rsp+1Ch] [rbp-4h]

  if ( a2 && a1 )
  {
    if ( (a2 & 0x80000000) != 0 )
      _exit(-2);
    chk = __read_chk(0LL, a1, a2 - 1, a2);
    if ( chk <= 0 )
    {
      puts("read error");
      _exit(1);
    }
    if ( a1[chk - 1] == 10 )
      a1[chk - 1] = 0;
  }
}
// A10: using guessed type __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000D3D) ----------------------------------------------------
int Menu()
{
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  puts(&byte_2E45);
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  if ( isLogginIn )
    puts(" 1. Bounty              ");
  else
    puts(" 1. Login               ");
  if ( isLogginIn )
    puts(" 2. Change password     ");
  else
    puts(" 2. Register            ");
  puts(" 3. Show Product        ");
  if ( isLogginIn )
  {
    puts(" 4. Change contact            ");
    puts(" 5. Remove user               ");
    puts(" 6. Userinfo                  ");
    puts(" 7. Logout                    ");
  }
  puts(" 0. Exit                ");
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  return printf("Your choice: ");
}
// 204068: using guessed type char isLogginIn;

//----- (0000000000000E22) ----------------------------------------------------
int sub_E22()
{
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  puts(&byte_2F86);
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  puts(" 1. Add new product     ");
  puts(" 2. Add new type        ");
  puts(" 3. Submit a bug report ");
  puts(" 4. Remove type         ");
  puts(" 5. Modify a bug report ");
  puts(" 6. Show vulnerability  ");
  puts(" 7. Evalute vulnerability");
  puts(" 8. Delete a bug report ");
  puts(" 0. Return              ");
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$");
  return printf("Your choice: ");
}

//----- (0000000000000ED6) ----------------------------------------------------
User *Register()
{
  User *result; // rax
  User *new_user; // [rsp+8h] [rbp-8h]

  new_user = (User *)calloc(1uLL, 0x58uLL);
  if ( !new_user )
  {
    puts("Error!");
    _exit(1);
  }
  new_user->uid = rand() ^ 0xDADADADADADADADALL;
  printf("Username:");
  read_input(new_user->username, 31);
  printf("Password:");
  read_input(new_user->password, 16);
  new_user->contact = (char *)calloc(1uLL, 0x20uLL);
  printf("Contact:");
  read_input(new_user->contact, 32);
  LODWORD(new_user->balance) = 0;
  LODWORD(new_user->report_count) = 0;
  if ( admin )
  {
    new_user->next = admin;
    result = new_user;
    admin = new_user;
  }
  else
  {
    admin = new_user;
    user_head = new_user;
    result = new_user;
    new_user->next = 0LL;
  }
  return result;
}

//----- (000000000000101E) ----------------------------------------------------
unsigned __int64 Login()
{
  User *current_user; // [rsp+8h] [rbp-48h]
  char s2[16]; // [rsp+10h] [rbp-40h] BYREF
  char s[40]; // [rsp+20h] [rbp-30h] BYREF
  unsigned __int64 v4; // [rsp+48h] [rbp-8h]

  v4 = __readfsqword(0x28u);
  memset(s, 0, 0x20uLL);
  memset(s2, 0, sizeof(s2));
  printf("Username:");
  read_input(s, 0x20u);
  printf("Password:");
  read_input(s2, 0x10u);
  if ( admin )
  {
    for ( current_user = admin; current_user; current_user = current_user->next )
    {
      if ( !strncmp(current_user->username, s, 0x1FuLL) && !strncmp(current_user->password, s2, 0xFuLL) )
      {
        isLogginIn = 1;
        puts("Login success !");
        user = current_user;
        return __readfsqword(0x28u) ^ v4;
      }
    }
  }
  puts("Invalid user or password !");
  return __readfsqword(0x28u) ^ v4;
}
// 204068: using guessed type char isLogginIn;

//----- (0000000000001157) ----------------------------------------------------
unsigned __int64 AddProduct()
{
  int index; // [rsp+0h] [rbp-60h]
  int new_product_id; // [rsp+4h] [rbp-5Ch]
  Product *new_product; // [rsp+8h] [rbp-58h]
  char buf[72]; // [rsp+10h] [rbp-50h] BYREF
  unsigned __int64 v5; // [rsp+58h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  memset(buf, 0, 0x40uLL);
  printf("Name of Product:");
  read_input(buf, 0x30u);
  for ( index = 0; index <= 7; ++index )
  {
    if ( Products[index] && !strcmp(Products[index]->name, buf) )
    {
      puts("Already have this product !");
      return __readfsqword(0x28u) ^ v5;
    }
  }
  for ( new_product_id = 0; new_product_id <= 7; ++new_product_id )
  {
    if ( !Products[new_product_id] )
    {
      new_product = (Product *)calloc(1uLL, 0x58uLL);
      if ( !new_product )
      {
        puts("Error !");
        _exit(-3);
      }
      memcpy(new_product, buf, 0x30uLL);
      memset(buf, 0, 0x40uLL);
      printf("Company:");
      read_input(buf, 0x20u);
      new_product->company = strdup(buf);
      new_product->bugs = 0LL;
      printf("Comment:");
      read_input(new_product->comment, 0x10u);
      Products[new_product_id] = new_product;
      return __readfsqword(0x28u) ^ v5;
    }
  }
  return __readfsqword(0x28u) ^ v5;
}

//----- (0000000000001355) ----------------------------------------------------
VulnType *__fastcall AllocateType(const char *type_name, int price)
{
  int index; // [rsp+10h] [rbp-10h]
  int type_id; // [rsp+14h] [rbp-Ch]
  VulnType *new_type; // [rsp+18h] [rbp-8h]

  if ( !type_name )
  {
    puts("Error !");
    _exit(-1);
  }
  for ( index = 0; index <= 7; ++index )
  {
    if ( VulnTypes[index] && !strcmp(VulnTypes[index]->name, type_name) )
      return 0LL;
  }
  for ( type_id = 0; type_id <= 7; ++type_id )
  {
    if ( !VulnTypes[type_id] )
    {
      new_type = (VulnType *)calloc(1uLL, 0x10uLL);
      new_type->name = strdup(type_name);
      new_type->price = price;
      new_type->ref_count = 1;
      VulnTypes[type_id] = new_type;
      return new_type;
    }
  }
  return 0LL;
}

//----- (000000000000148F) ----------------------------------------------------
__int64 __fastcall FreeType(const char *name)
{
  int type_id; // [rsp+1Ch] [rbp-4h]

  if ( !name )
  {
    puts("Error !");
    _exit(-1);
  }
  for ( type_id = 0; type_id <= 7; ++type_id )
  {
    if ( VulnTypes[type_id] && !strcmp(VulnTypes[type_id]->name, name) && VulnTypes[type_id]->ref_count == 1 )
    {
      free(VulnTypes[type_id]->name);
      free(VulnTypes[type_id]);
      VulnTypes[type_id] = 0LL;
      return 1LL;
    }
  }
  return 0LL;
}

//----- (00000000000015B2) ----------------------------------------------------
void AddVulnType()
{
  unsigned int size; // [rsp+8h] [rbp-18h] not size_t anymore
  int price; // [rsp+Ch] [rbp-14h]
  char *type_name; // [rsp+10h] [rbp-10h]
  char *types; // [rsp+18h] [rbp-8h]

  printf("Size:");
  size = read_long();
  types = (char *)calloc(1uLL, size);
  puts("(Note:You can add many types at the same time)");
  puts("(Example: SQLI,Buffer overflow,LFI)");
  printf("Type:");
  read_input(types, size);
  for ( type_name = strtok(types, ","); type_name; type_name = strtok(0LL, ",") )
  {
    printf("type: %s\n", type_name);
    printf("Price:");
    price = read_long();
    if ( AllocateType(type_name, price) )
      puts("Success !");
    else
      puts(&byte_319F);
  }
  free(types);
}

//----- (00000000000016F2) ----------------------------------------------------
int ShowTypes()
{
  VulnType *v0; // rax
  int i; // [rsp+Ch] [rbp-4h]

  LODWORD(v0) = puts("*********************************");
  for ( i = 0; i <= 7; ++i )
  {
    v0 = VulnTypes[i];
    if ( v0 )
    {
      printf("ID > %d\n", (unsigned int)i);
      printf("Type > %s\n", VulnTypes[i]->name);
      printf("Price > %u\n", (unsigned int)VulnTypes[i]->price);
      LODWORD(v0) = puts("*********************************");
    }
  }
  return (int)v0;
}

//----- (00000000000017BF) ----------------------------------------------------
unsigned __int64 RemoveVulnType()
{
  __int64 size; // [rsp+0h] [rbp-60h]
  char *type_name; // [rsp+8h] [rbp-58h]
  char s[32]; // [rsp+10h] [rbp-50h] BYREF
  char v4[40]; // [rsp+30h] [rbp-30h] BYREF
  unsigned __int64 v5; // [rsp+58h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  printf("Size:");
  size = read_long();
  memset(s, 0, sizeof(s));                      // for nothing?
  memset(v4, 0, 32uLL);
  type_name = (char *)calloc(1uLL, size);
  printf("Type:");
  read_input(type_name, size);
  if ( (unsigned __int8)FreeType(type_name) != 1 )
    puts("No such type !");
  else
    puts("success !");
  free(type_name);
  return __readfsqword(0x28u) ^ v5;
}
// 17BF: using guessed type char s[32];
// 17BF: using guessed type char var_30[40];

//----- (00000000000018BB) ----------------------------------------------------
int ShowProduct()
{
  Product *v0; // rax
  int i; // [rsp+Ch] [rbp-4h]

  LODWORD(v0) = puts(">-------------------------------<");
  for ( i = 0; i <= 7; ++i )
  {
    v0 = Products[i];
    if ( v0 )
    {
      printf("ID > %d\n", (unsigned int)i);
      printf("Name > %s\n", Products[i]->name);
      printf("Company > %s\n", Products[i]->company);
      LODWORD(v0) = puts(">-------------------------------<");
    }
  }
  return (int)v0;
}

//----- (0000000000001987) ----------------------------------------------------
int ShowBugDetail()
{
  BugReport *v0; // rax
  BugReport *bugs; // [rsp+0h] [rbp-10h]
  unsigned __int64 product_id; // [rsp+8h] [rbp-8h]

  printf("Product ID:");
  product_id = read_long();
  if ( product_id > 7 )
  {
    puts("Out of bound !");
    _exit(-5);
  }
  if ( Products[product_id] )
  {
    printf("ID > %lu\n", product_id);
    printf("Name > %s\n", Products[product_id]->name);
    printf("Company > %s\n", Products[product_id]->company);
    if ( Products[product_id]->bugs )
    {
      bugs = Products[product_id]->bugs;
      puts(&byte_3260);
      do
      {
        if ( user == user_head || bugs->owner == user )
        {
          printf("Bug ID > %u\n", LODWORD(bugs->id));
          printf("Title > %s\n", bugs->title);
          printf("Type > %s\n", bugs->type->name);
          printf("Reporter > %s\n", bugs->owner->username);
          printf("Descripton > %s\n", bugs->description);
          bugs = bugs->next;
          puts(&byte_3260);
        }
        v0 = Products[product_id]->bugs;
      }
      while ( bugs != v0 );
    }
    else
    {
      LODWORD(v0) = puts("No bug!");
    }
  }
  else
  {
    LODWORD(v0) = puts("No such product !");
  }
  return (int)v0;
}

//----- (0000000000001BDF) ----------------------------------------------------
Product *__fastcall AddReportToProduct(Product *a1, BugReport *a2)
{
  Product *result; // rax
  BugReport *prev; // [rsp+18h] [rbp-8h]

  if ( !a1 || !a2 )
  {
    puts("Error !");
    _exit(-1337);
  }
  if ( a1->bugs )
  {
    prev = a1->bugs->prev;
    prev->next = a2;
    a1->bugs->prev = a2;
    a2->next = a1->bugs;
    result = (Product *)a2;
    a2->prev = prev;
  }
  else
  {
    a2->next = a2;
    a2->prev = a2;
    result = a1;
    a1->bugs = a2;
  }
  return result;
}

//----- (0000000000001CB6) ----------------------------------------------------
Product *__fastcall RemoveBugFromProduct(Product *a1, BugReport *a2)
{
  Product *result; // rax
  BugReport *next; // [rsp+10h] [rbp-10h]
  BugReport *prev; // [rsp+18h] [rbp-8h]

  if ( !a1 || !a2 )
  {
    puts("Error !");
    _exit(-1338);
  }
  next = a2->next;
  prev = a2->prev;
  if ( a2 != next->prev || a2 != prev->next )
  {
    puts("Memory currpution !");
    _exit(56746);
  }
  if ( next == a2 && prev == a2 )
  {
    result = a1;
    a1->bugs = 0LL;
  }
  else if ( a2 == a1->bugs )
  {
    next->prev = prev;
    prev->next = next;
    result = a1;
    a1->bugs = next;
  }
  else
  {
    next->prev = prev;
    result = (Product *)prev;
    prev->next = next;
  }
  return result;
}

//----- (0000000000001DD3) ----------------------------------------------------
void SubmitReport()
{
  unsigned __int64 size; // [rsp+10h] [rbp-20h]
  BugReport *new_report; // [rsp+18h] [rbp-18h]
  Product *product; // [rsp+20h] [rbp-10h]
  unsigned __int64 product_id; // [rsp+28h] [rbp-8h]
  unsigned __int64 type_id; // [rsp+28h] [rbp-8h]

  new_report = (BugReport *)calloc(1uLL, 0x140uLL);
  if ( !new_report )
  {
    puts("Error !");
    _exit(-4);
  }
  ShowProduct();
  printf("Product ID:");
  product_id = read_long();
  if ( product_id <= 7
    && Products[product_id]
    && (product = Products[product_id], ShowTypes(), printf("Type:"), type_id = read_long(), type_id <= 7)
    && VulnTypes[type_id] )
  {
    new_report->type = VulnTypes[type_id];
    ++new_report->type->ref_count;
    new_report->owner = user;
    ++LODWORD(user->report_count);
    printf("Title:");
    read_input(new_report->title, 255);
    printf("ID:");
    LODWORD(new_report->id) = read_long();
    printf("Length of descripton:");
    size = read_long();
    if ( size <= 0x407 )
      size = 0x408LL;
    new_report->description = (char *)calloc(1uLL, size);// not using malloc
    if ( !new_report->description )
    {
      puts("Error !");
      _exit(-5);
    }
    printf("Descripton:");                      // not more filling random bytes
    read_input(new_report->description, size);
    new_report->description_size = size;
    new_report->next = 0LL;
    new_report->prev = 0LL;
    new_report->evaluated = 0;
    AddReportToProduct(product, new_report);
  }
  else
  {
    puts(&byte_319F);
    free(new_report);
  }
}
// 16F2: using guessed type __int64 ShowTypes(void);

//----- (00000000000020BA) ----------------------------------------------------
int DeleteReport()
{
  int bug_id; // [rsp+Ch] [rbp-14h]
  BugReport *bugs; // [rsp+10h] [rbp-10h]
  unsigned __int64 product_id; // [rsp+18h] [rbp-8h]

  printf("Product ID:");
  product_id = read_long();
  if ( product_id > 7 )
    return puts("Invalid !");
  if ( !Products[product_id] )
    return puts("No such product !");
  printf("ID > %lu\n", product_id);
  printf("Name > %s\n", Products[product_id]->name);
  printf("Company > %s\n", Products[product_id]->company);
  if ( !Products[product_id]->bugs )
    return puts("No bug !");
  printf("Bug ID:");
  bug_id = read_long();
  bugs = Products[product_id]->bugs;
  do
  {
    if ( bug_id == LODWORD(bugs->id) )
    {
      if ( bugs->owner == user && bugs->evaluated != 1 )
      {
        --bugs->type->ref_count;
        --LODWORD(bugs->owner->report_count);
        RemoveBugFromProduct(Products[product_id], bugs);
        free(bugs->description);
        free(bugs);
        return puts("Done!");
      }
      puts("You are not the owner or it expired");
    }
    bugs = bugs->next;
  }
  while ( bugs != Products[product_id]->bugs );
  return puts("No such bug !");
}

//----- (0000000000002321) ----------------------------------------------------
unsigned __int64 ModifyReport()
{
  int bug_id; // [rsp+4h] [rbp-3Ch]
  BugReport *bugs; // [rsp+8h] [rbp-38h]
  unsigned __int64 product_id; // [rsp+10h] [rbp-30h]
  unsigned __int64 type_id; // [rsp+20h] [rbp-20h]
  char choice[8]; // [rsp+30h] [rbp-10h] BYREF
  unsigned __int64 v6; // [rsp+38h] [rbp-8h]

  v6 = __readfsqword(0x28u);
  printf("Product ID:");
  product_id = read_long();
  if ( product_id <= 7 )
  {
    if ( Products[product_id] )
    {
      printf("ID > %lu\n", product_id);
      printf("Name > %s\n", Products[product_id]->name);
      printf("Company > %s\n", Products[product_id]->company);
      if ( Products[product_id]->bugs )
      {
        printf("Bug ID:");
        bug_id = read_long();
        bugs = Products[product_id]->bugs;
        while ( bug_id != LODWORD(bugs->id) )
        {
          bugs = bugs->next;
          if ( bugs == Products[product_id]->bugs )
          {
            puts("No such bug !");
            return __readfsqword(0x28u) ^ v6;
          }
        }
        printf("Title:");
        read_input(bugs->title, 0xFFu);
        printf("Length of descripton:");
        bugs->description_size = read_long();
        if ( bugs->description_size <= 0x407uLL )
          bugs->description_size = 1032LL;
        free(bugs->description);
        bugs->description = (char *)calloc(1uLL, bugs->description_size);
        if ( !bugs->description )
        {
          puts("Error!");
          _exit(-9);
        }
        printf("Descripton:");
        read_input(bugs->description, bugs->description_size);
        printf("Do you want to change to another type ? ");
        read_input(choice, 3u);
        if ( choice[0] == 'y' )
        {
          ShowTypes();
          printf("Type:");
          type_id = read_long();
          if ( type_id <= 7 && VulnTypes[type_id] )
          {
            --bugs->type->ref_count;
            bugs->type = VulnTypes[type_id];
            ++bugs->type->ref_count;
          }
        }
        else
        {
          puts("Use old type !");
        }
      }
      else
      {
        puts("No bug !");
      }
    }
    else
    {
      puts("No such product !");
    }
  }
  return __readfsqword(0x28u) ^ v6;
}
// 16F2: using guessed type __int64 ShowTypes(void);
// 2321: using guessed type char choice[8];

//----- (00000000000026DF) ----------------------------------------------------
int EvalVuln()
{
  int i; // [rsp+0h] [rbp-10h]
  BugReport *bugs; // [rsp+8h] [rbp-8h]

  if ( user != (User *)user_head )
    return puts("Permission denied !");
  for ( i = 0; i <= 7; ++i )
  {
    if ( Products[i] && Products[i]->bugs )
    {
      bugs = Products[i]->bugs;
      do
      {
        if ( bugs->evaluated != 1 )
        {
          if ( bugs->type )
          {
            bugs->evaluated = 1;
            LODWORD(bugs->owner->balance) += bugs->type->price;
          }
        }
        bugs = bugs->next;
      }
      while ( bugs != Products[i]->bugs );
    }
  }
  return puts("Done !");
}
// 204078: using guessed type __int64 qword_204078;

//----- (0000000000002836) ----------------------------------------------------
unsigned __int64 UserInfo()
{
  unsigned __int64 v1; // [rsp+98h] [rbp-8h]

  v1 = __readfsqword(0x28u);
  puts("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
  printf("Name > %s\n", user->username);
  printf("Price > %u\n", LODWORD(user->balance));
  printf("Uid > %lu\n", user->uid);
  puts("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
  return __readfsqword(0x28u) ^ v1;
}

//----- (00000000000028F0) ----------------------------------------------------
void RemoveUser()
{
  if ( !LODWORD(user->balance) && !LODWORD(user->report_count) && user != (User *)user_head )
  {
    if ( user == admin )
    {
      admin = admin->next;
      free(user);
    }
    else
    {
      while ( admin->next && admin->next != user )
        ;
      admin->next = user->next;
    }
    user = 0LL;
    isLogginIn = 0;
  }
}
// 204068: using guessed type char isLogginIn;
// 204078: using guessed type __int64 qword_204078;

//----- (00000000000029C8) ----------------------------------------------------
void ChangePassword()
{
  if ( user && user == user_head )
  {
    printf("New password:");
    read_input(user->password, 0x10u);
  }
  else
  {
    puts("permission denied");
  }
}

//----- (0000000000002A21) ----------------------------------------------------
void ChangeContact()
{
  if ( user && user == user_head )
  {
    printf("Contact:");
    read_input(user->contact, 0x20u);
  }
  else
  {
    puts("permission denied");
  }
}

//----- (0000000000002A7E) ----------------------------------------------------
__int64 Bounty()
{
  __int64 result; // rax

  while ( 1 )
  {
    BountyMenu();
    result = read_long();
    switch ( result )
    {
      case 0LL:
        return result;
      case 1LL:
        AddProduct();
        break;
      case 2LL:
        AddVulnType();
        break;
      case 3LL:
        SubmitReport();
        break;
      case 4LL:
        RemoveVulnType();
        break;
      case 5LL:
        ModifyReport();
        break;
      case 6LL:
        ShowBugDetail();
        break;
      case 7LL:
        EvalVuln();
        break;
      case 8LL:
        DeleteReport();
        break;
      default:
        puts("Invalid Choice");
        break;
    }
  }
}

//----- (0000000000002B43) ----------------------------------------------------
__int64 sub_2B43()
{
  stream = fopen("/dev/urandom", "r");
  if ( !stream )
    _exit(-1);
  setvbuf(stdin, 0LL, 2, 0LL);
  setvbuf(stdout, 0LL, 2, 0LL);
  setvbuf(stderr, 0LL, 2, 0LL);
  setvbuf(stream, 0LL, 2, 0LL);
  signal(14, handler);
  AllocateType("RCE", 10000LL);
  AllocateType("XSS", 500LL);
  return AllocateType("DoS", 777LL);
}
// 1355: using guessed type __int64 __fastcall sub_1355(_QWORD, _QWORD);

//----- (0000000000002C36) ----------------------------------------------------
void __fastcall __noreturn main(const char *a1, char **a2, char **a3)
{
  setup();
  while ( 1 )
  {
    Menu();
    switch ( read_long() )
    {
      case 0LL:
        _exit(0);
      case 1LL:
        if ( isLogginIn )
          Bounty();
        else
          Login(a1, a2);
        break;
      case 2LL:
        if ( isLogginIn )
          ChangePassword();
        else
          Register();
        break;
      case 3LL:
        ShowProduct();
        break;
      case 4LL:
        if ( isLogginIn )
          ChangeContact();
        break;
      case 5LL:
        if ( isLogginIn )
          RemoveUser();
        break;
      case 6LL:
        if ( isLogginIn )
          UserInfo();
        break;
      case 7LL:
        if ( isLogginIn )
        {
          isLogginIn = 0;
          user = 0LL;
        }
        break;
      default:
        a1 = "Invalid Choice";
        puts("Invalid Choice");
        break;
    }
  }
}
// 101E: using guessed type __int64 __fastcall Login(_QWORD, _QWORD);
// 204068: using guessed type char isLogginIn;

//----- (0000000000002D90) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  v4 = &off_203D38 - &funcs_2DD9;
  init_proc();
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&funcs_2DD9 + i))(a1, a2, a3);
  }
}
// 9B0: using guessed type __int64 init_proc(void);
// C10: using guessed type __int64 __fastcall sub_C10(_QWORD, _QWORD, _QWORD);
// 203D30: using guessed type __int64 (__fastcall *funcs_2DD9)();
// 203D38: using guessed type __int64 (__fastcall *off_203D38)();

//----- (0000000000002E04) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=78 queued=37 decompiled=37 lumina nreq=0 worse=0 better=0
// ALL OK, 37 function(s) have been successfully decompiled
