/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_9F0();
// void __noreturn _exit(int status);
// __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int puts(const char *s);
// int setenv(const char *name, const char *value, int replace);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// unsigned int alarm(unsigned int seconds);
// __int64 atoll(const char *nptr);
// int strcmp(const char *s1, const char *s2);
// __sighandler_t signal(int sig, __sighandler_t handler);
// int fprintf(FILE *stream, const char *format, ...);
// __int64 syscall(__int64 sysno, ...);
// int prctl(int option, ...);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// char *strstr(const char *haystack, const char *needle);
// int __fastcall _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *deregister_tm_clones();
__int64 register_tm_clones(void); // weak
void *_do_global_dtors_aux();
__int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall bpf_resolve_jumps(__int64 a1, __int64 a2, unsigned __int64 a3);
__int64 __fastcall seccomp_bpf_label(int *a1, const char *a2);
unsigned __int64 my_sandbox();
void __noreturn handler();
unsigned int init_proc();
__int64 read_long(); // weak
_BYTE *__fastcall read_input(__int64 a1, unsigned int a2);
int __fastcall main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(void); // idb
void term_proc();
// int setenv(const char *name, const char *value, int replace);
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 syscall(__int64 sysno, ...);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
__int64 (__fastcall *_frame_dummy_init_array_entry)() = &frame_dummy; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
void *_dso_handle = &_dso_handle; // idb
_UNKNOWN _bss_start; // weak
FILE *stdout; // idb
FILE *stdin; // idb
__int64 environ; // weak
FILE *stderr; // idb
char completed_7697; // weak


//----- (00000000000009D8) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 2020F8: using guessed type __int64 _gmon_start__(void);

//----- (00000000000009F0) ----------------------------------------------------
void sub_9F0()
{
  JUMPOUT(0LL);
}
// 9F6: control flows out of bounds to 0

//----- (0000000000000B20) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// B26: positive sp value 8 has been found
// B2D: variable 'v3' is possibly undefined

//----- (0000000000000B50) ----------------------------------------------------
void *deregister_tm_clones()
{
  return &_bss_start;
}

//----- (0000000000000B90) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}
// B90: using guessed type __int64 register_tm_clones();

//----- (0000000000000BE0) ----------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // rax

  if ( !completed_7697 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_7697 = 1;
  }
  return result;
}
// 202048: using guessed type char completed_7697;

//----- (0000000000000C20) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// B90: using guessed type __int64 register_tm_clones(void);
// C20: using guessed type __int64 frame_dummy();

//----- (0000000000000C2A) ----------------------------------------------------
__int64 __fastcall bpf_resolve_jumps(__int64 a1, __int64 a2, unsigned __int64 a3)
{
  int v4; // eax
  unsigned __int64 i; // [rsp+28h] [rbp-18h]
  __int64 v6; // [rsp+38h] [rbp-8h]

  if ( !a3 || a3 > 0x1000 )
    return 0xFFFFFFFFLL;
  for ( i = 0LL; i < a3; ++i )
  {
    v6 = 8 * (a3 - i - 1) + a2;
    if ( *(_WORD *)v6 == 5 )
    {
      v4 = (*(unsigned __int8 *)(v6 + 2) << 8) | *(unsigned __int8 *)(v6 + 3);
      if ( v4 == 65278 )
      {
        if ( *(_DWORD *)(16LL * *(unsigned int *)(v6 + 4) + a1 + 16) != -1 )
        {
          fprintf(stderr, "Duplicate label use: '%s'\n", *(const char **)(16LL * *(unsigned int *)(v6 + 4) + a1 + 8));
          return 1LL;
        }
        *(_DWORD *)(16LL * *(unsigned int *)(v6 + 4) + a1 + 16) = a3 - i - 1;
        *(_DWORD *)(v6 + 4) = 0;
        *(_BYTE *)(v6 + 2) = 0;
        *(_BYTE *)(v6 + 3) = 0;
      }
      else if ( v4 == 0xFFFF )
      {
        if ( *(_DWORD *)(16LL * *(unsigned int *)(v6 + 4) + a1 + 16) == -1 )
        {
          fprintf(stderr, "Unresolved label: '%s'\n", *(const char **)(16LL * *(unsigned int *)(v6 + 4) + a1 + 8));
          return 1LL;
        }
        *(_DWORD *)(v6 + 4) = *(_DWORD *)(16LL * *(unsigned int *)(v6 + 4) + a1 + 16) - (a3 - i);
        *(_BYTE *)(v6 + 2) = 0;
        *(_BYTE *)(v6 + 3) = 0;
      }
    }
  }
  return 0LL;
}

//----- (0000000000000E23) ----------------------------------------------------
__int64 __fastcall seccomp_bpf_label(int *a1, const char *a2)
{
  unsigned int v3; // [rsp+1Ch] [rbp-14h]
  int *v4; // [rsp+20h] [rbp-10h]
  int *v5; // [rsp+28h] [rbp-8h]

  v4 = a1 + 2;
  if ( *a1 == 256 )
  {
    fwrite("Too many labels\n", 1uLL, 0x10uLL, stderr);
    _exit(1);
  }
  if ( *a1 )
  {
    v5 = &v4[4 * *a1];
    v3 = 0;
    while ( v4 < v5 )
    {
      if ( !strcmp(a2, *(const char **)v4) )
        return v3;
      v4 += 4;
      ++v3;
    }
    *(_QWORD *)v4 = a2;
    v4[2] = -1;
    ++*a1;
    return v3;
  }
  else
  {
    *(_QWORD *)v4 = a2;
    a1[4] = -1;
    ++*a1;
    return 0LL;
  }
}

//----- (0000000000000F2B) ----------------------------------------------------
unsigned __int64 my_sandbox()
{
  __int16 v1; // [rsp+0h] [rbp-11A0h] BYREF
  char *v2; // [rsp+8h] [rbp-1198h]
  char v3[384]; // [rsp+10h] [rbp-1190h] BYREF
  char v4[4104]; // [rsp+190h] [rbp-1010h] BYREF
  unsigned __int64 v5; // [rsp+1198h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  memset(v4, 0, sizeof(v4));
  qmemcpy(v3, " ", 0x178uLL);
  bpf_resolve_jumps(v4, v3, 47LL);
  v1 = 47;
  v2 = v3;
  prctl(38, 1LL, 0LL, 0LL, 0LL);
  prctl(22, 2LL, &v1);
  return __readfsqword(0x28u) ^ v5;
}
// C2A: using guessed type __int64 __fastcall bpf_resolve_jumps(_QWORD, _QWORD, _QWORD);

//----- (0000000000001006) ----------------------------------------------------
void __noreturn handler()
{
  puts("Timeout !");
  _exit(1);
}

//----- (0000000000001027) ----------------------------------------------------
unsigned int init_proc()
{
  setvbuf(stdin, 0LL, 2, 0LL);
  setvbuf(stdout, 0LL, 2, 0LL);
  setvbuf(stderr, 0LL, 2, 0LL);
  signal(14, (__sighandler_t)handler);
  return alarm(0x12Cu);
}

//----- (00000000000010A3) ----------------------------------------------------
__int64 read_long()
{
  char nptr[24]; // [rsp+10h] [rbp-20h] BYREF
  unsigned __int64 v2; // [rsp+28h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  __read_chk(0LL, nptr, 16LL, 17LL);
  return atoll(nptr);
}
// A10: using guessed type __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 10A3: using guessed type __int64 read_long();

//----- (0000000000001104) ----------------------------------------------------
_BYTE *__fastcall read_input(__int64 a1, unsigned int a2)
{
  _BYTE *result; // rax
  int chk; // [rsp+1Ch] [rbp-4h]

  chk = __read_chk(0LL, a1, a2, a2);
  if ( chk <= 0 )
  {
    puts("read error");
    _exit(1);
  }
  result = (_BYTE *)*(unsigned __int8 *)(chk - 1LL + a1);
  if ( (_BYTE)result == 10 )
  {
    result = (_BYTE *)(chk - 1LL + a1);
    *result = 0;
  }
  return result;
}
// A10: using guessed type __int64 __fastcall __read_chk(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000117B) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  char s[256]; // [rsp+10h] [rbp-1110h] BYREF
  char value[4104]; // [rsp+110h] [rbp-1010h] BYREF
  unsigned __int64 v6; // [rsp+1118h] [rbp-8h]

  v6 = __readfsqword(0x28u);
  init_proc(argc, argv, envp);
  memset(s, 0, sizeof(s));
  memset(value, 0, 4096uLL);
  printf("Name:");
  read_input(s, 248LL);
  if ( strstr(s, "LD") || strstr(s, "MALLOC") )
  {
    printf("Danger!");
    _exit(-1);
  }
  printf("Value:");
  read_input(value, 512LL);
  setenv(s, value, 1);
  my_sandbox();
  syscall(322LL, 100LL, "./bounty_program", argv, environ, 0LL);
  return 0;
}
// F2B: using guessed type __int64 my_sandbox(void);
// 1027: using guessed type __int64 __fastcall init_proc(_QWORD, _QWORD, _QWORD);
// 1104: using guessed type __int64 __fastcall read_input(_QWORD, _QWORD);
// 202038: using guessed type __int64 environ;

//----- (0000000000001300) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  v4 = &_do_global_dtors_aux_fini_array_entry - &_frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&_frame_dummy_init_array_entry + i))(a1, a2, a3);
  }
}
// C20: using guessed type __int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD);
// 201D38: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry)();
// 201D40: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000001374) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=56 queued=17 decompiled=17 lumina nreq=0 worse=0 better=0
// ALL OK, 17 function(s) have been successfully decompiled
