/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
void sub_D50();
// int mprotect(void *addr, size_t len, int prot);
// int printf(const char *format, ...);
// int close(int fd);
// void __noreturn abort(void);
// __int64 __gmon_start__(void); weak
// int puts(const char *s);
// ssize_t read(int fd, void *buf, size_t nbytes);
// void *malloc(size_t size);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __pid_t getpid(void);
// void bzero(void *s, size_t n);
// void free(void *ptr);
// int __fastcall __cxa_finalize(void *);
// int kill(__pid_t pid, int sig);
// char *strstr(const char *haystack, const char *needle);
// __int64 strtol(const char *nptr, char **endptr, int base);
// char *strchr(const char *s, int c);
// int asprintf(char **ptr, const char *fmt, ...);
// void *__fastcall __cxa_allocate_exception(size_t thrown_size);
// void *calloc(size_t nmemb, size_t size);
// void __fastcall __noreturn __cxa_throw(void *, struct type_info *lptinfo, void (__fastcall *)(void *));
// void __cxa_end_catch(void);
// void *__fastcall __cxa_begin_catch(void *);
// void *realloc(void *ptr, size_t size);
// ssize_t write(int fd, const void *buf, size_t n);
// void _Unwind_Resume(struct _Unwind_Exception *);
// unsigned __int64 strtoul(const char *nptr, char **endptr, int base);
// int open(const char *file, int oflag, ...);
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
__int64 (**deregister_tm_clones())(void);
__int64 register_tm_clones(void); // weak
__int64 (**_do_global_dtors_aux())(void);
__int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall read_until(int fd, char a2, char *a3, unsigned int a4); // idb
unsigned __int64 __fastcall get_mapped_area(const char *needle, const char *a2, unsigned __int64 *a3, unsigned __int64 *a4);
unsigned __int64 secure_self(void);
ssize_t __fastcall secure_read(char *buf, size_t nbytes);
unsigned __int64 init(void);
int help(void);
unsigned __int64 list(void);
unsigned __int64 note(void);
unsigned __int64 punish(void);
unsigned __int64 interact(void);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void _libc_csu_fini(void); // idb
void term_proc();
// void __noreturn abort(void);
// void bzero(void *s, size_t n);
// int __fastcall _cxa_finalize(void *);
// void *__fastcall _cxa_allocate_exception(size_t thrown_size);
// ssize_t write(int fd, const void *buf, size_t n);
// __int64 Jv_RegisterClasses(void); weak
// __int64 ITM_deregisterTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
_UNKNOWN _JCR_LIST__; // weak
void *_dso_handle = &_dso_handle; // idb
char _bss_start; // weak
_UNKNOWN unk_203027; // weak
char occupied; // weak
void *dst_whitelist; // idb
Prisoner *head;
// extern _UNKNOWN `typeinfo for'int; weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0000000000000D30) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (void *)__gmon_start__();
  return result;
}
// DA0: using guessed type __int64 __gmon_start__(void);

//----- (0000000000000D50) ----------------------------------------------------
void sub_D50()
{
  JUMPOUT(0LL);
}
// D56: control flows out of bounds to 0

//----- (0000000000000F50) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  init();
  while ( 1 )
    interact();
}

//----- (0000000000000FEE) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// FF4: positive sp value 8 has been found
// FFB: variable 'v3' is possibly undefined

//----- (0000000000001020) ----------------------------------------------------
__int64 (**deregister_tm_clones())(void)
{
  __int64 (**result)(void); // rax

  result = (__int64 (**)(void))(&unk_203027 - (_UNKNOWN *)&_bss_start);
  if ( (unsigned __int64)(&unk_203027 - (_UNKNOWN *)&_bss_start) > 0xE )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      return (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return result;
}
// 203020: using guessed type char _bss_start;
// 203150: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000001060) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}
// 1060: using guessed type __int64 register_tm_clones();

//----- (00000000000010B0) ----------------------------------------------------
__int64 (**_do_global_dtors_aux())(void)
{
  __int64 (**result)(void); // rax

  if ( !_bss_start )
  {
    if ( &_cxa_finalize )
      __cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 203020: using guessed type char _bss_start;

//----- (00000000000010F0) ----------------------------------------------------
__int64 frame_dummy()
{
  if ( _JCR_LIST__ && &Jv_RegisterClasses )
    Jv_RegisterClasses();
  return register_tm_clones();
}
// 1060: using guessed type __int64 register_tm_clones(void);
// 10F0: using guessed type __int64 frame_dummy();
// 203148: using guessed type __int64 Jv_RegisterClasses(void);

//----- (0000000000001120) ----------------------------------------------------
__int64 __fastcall read_until(int fd, char a2, char *a3, unsigned int a4)
{
  unsigned int v6; // ebx
  __int64 v7; // rdx
  char buf; // [rsp+7h] [rbp-41h] BYREF
  unsigned __int64 v10; // [rsp+8h] [rbp-40h]

  v6 = 0;
  v10 = __readfsqword(0x28u);
  while ( read(fd, &buf, 1uLL) == 1 && v6 < a4 && buf != a2 )
  {
    v7 = v6++;
    a3[v7] = buf;
  }
  a3[v6] = 0;
  return v6;
}

//----- (00000000000011C0) ----------------------------------------------------
unsigned __int64 __fastcall get_mapped_area(
        const char *needle,
        const char *a2,
        unsigned __int64 *a3,
        unsigned __int64 *a4)
{
  int v6; // ebp
  char *v7; // rax
  char *v8; // rax
  char v10[264]; // [rsp+0h] [rbp-148h] BYREF
  unsigned __int64 v11; // [rsp+108h] [rbp-40h]

  v11 = __readfsqword(0x28u);
  memset(v10, 0, 0x100uLL);
  v6 = open("/proc/self/maps", 256);
  if ( v6 >= 0 )
  {
    while ( (unsigned int)read_until(v6, 10, v10, 0xFFu) )
    {
      if ( strstr(v10, needle) && strstr(v10, a2) )
      {
        v7 = strchr(v10, 45);
        if ( !v7 )
          break;
        *v7 = 0;
        v8 = strchr(v7 + 1, 32);
        if ( !v8 )
          break;
        *v8 = 0;
        *a3 = strtoul(v10, 0LL, 16);
        *a4 = strtoul(&v10[strlen(v10) + 1], 0LL, 16);
      }
    }
    close(v6);
  }
  return __readfsqword(0x28u) ^ v11;
}

//----- (0000000000001330) ----------------------------------------------------
unsigned __int64 secure_self(void)
{
  unsigned __int64 v0; // rax
  _QWORD *v1; // rcx
  _QWORD *v2; // rdi
  unsigned __int64 v3; // rax
  unsigned __int64 v5; // [rsp+8h] [rbp-30h] BYREF
  unsigned __int64 v6; // [rsp+10h] [rbp-28h] BYREF
  unsigned __int64 v7; // [rsp+18h] [rbp-20h]

  v7 = __readfsqword(0x28u);
  v5 = 0LL;
  v6 = 0LL;
  dst_whitelist = mmap(0LL, 0x1000uLL, 3, 34, 0, 0LL);
  if ( dst_whitelist == (void *)-1LL )
    goto LABEL_8;
  get_mapped_area("heap", "rw-p", &v5, &v6);
  if ( !v5 )
    goto LABEL_8;
  v0 = v6;
  if ( !v6 )
    goto LABEL_8;
  v1 = dst_whitelist;
  *(_QWORD *)dst_whitelist = v5;
  v1[1] = v0;
  v6 = 0LL;
  v5 = 0LL;
  get_mapped_area("heap", "rw-p", &v5, &v6);
  if ( !v5
    || !v6
    || (v2 = dst_whitelist,
        v3 = v5 + 2576,
        *((_QWORD *)dst_whitelist + 2) = v5 + 2240,
        v2[3] = v3,
        mprotect(v2, 0x1000uLL, 1) < 0) )
  {
LABEL_8:
    abort();
  }
  return __readfsqword(0x28u) ^ v7;
}

//----- (0000000000001460) ----------------------------------------------------
ssize_t __fastcall secure_read(char *buf, size_t nbytes)
{
  unsigned __int64 v2; // r8
  unsigned __int64 v3; // rcx
  char *v4; // rax
  unsigned __int64 v6; // [rsp+8h] [rbp-10h]

  v6 = __readfsqword(0x28u);
  v2 = *(_QWORD *)dst_whitelist;
  if ( !*(_QWORD *)dst_whitelist )
    return __readfsqword(0x28u) ^ v6;
  v3 = *((_QWORD *)dst_whitelist + 1);
  if ( !v3 )
    return __readfsqword(0x28u) ^ v6;
  v4 = (char *)dst_whitelist + 24;
  while ( (unsigned __int64)buf > v3 || (unsigned __int64)buf < v2 || (unsigned __int64)&buf[(unsigned int)nbytes] > v3 )
  {
    v2 = *((_QWORD *)v4 - 1);
    if ( v2 )
    {
      v4 += 16;
      v3 = *((_QWORD *)v4 - 2);
      if ( v3 )
        continue;
    }
    return __readfsqword(0x28u) ^ v6;
  }
  return read(0, buf, (unsigned int)nbytes);    // only heap write is allowed
}

//----- (0000000000001500) ----------------------------------------------------
unsigned __int64 init(void)
{
  int prisoner_fd; // r14d
  int v1; // r13d
  Prisoner *v2; // rbp
  Prisoner *prisoner; // rax
  Prisoner *v4; // rbx
  char *v5; // rax
  char *v6; // rbp
  const char *v7; // r15
  char *v8; // rax
  const char *v9; // rbp
  char *v10; // rax
  char *v11; // r15
  char v13[136]; // [rsp+0h] [rbp-C8h] BYREF
  unsigned __int64 v14; // [rsp+88h] [rbp-40h]

  v14 = __readfsqword(0x28u);
  memset(v13, 0, 0x80uLL);
  prisoner_fd = open("prisoner", 256);
  if ( prisoner_fd < 0 )
abort:
    abort();
  v1 = 0;
  v2 = 0LL;
  while ( (unsigned int)read_until(prisoner_fd, 10, v13, 0x80u) )
  {
    prisoner = (Prisoner *)calloc(1uLL, 0x40uLL);
    v4 = prisoner;
    head = prisoner;
    if ( !prisoner )
      goto abort;
    prisoner->next = v2;
    v5 = strchr(v13, 58);
    v6 = v5;
    if ( v5 )
      *v5 = 0;
    v7 = v5 + 1;
    asprintf(&v4->name, "%s", v13);
    v8 = strchr(v6 + 1, 58);
    if ( v8 )
      *v8 = 0;
    v9 = v8 + 1;
    asprintf(&v4->nickname, "%s", v7);
    v10 = strchr(v9, 58);
    v11 = v10;
    if ( v10 )
      *v10 = 0;
    v4->age = strtol(v9, 0LL, 10);
    v2 = v4;
    asprintf(&v4->sentence, "%s", v11 + 1);
    v4->cell_number = v1++;
    v4->risk = "High";
  }
  close(prisoner_fd);
  secure_self();
  return __readfsqword(0x28u) ^ v14;
}

//----- (00000000000016A0) ----------------------------------------------------
int help(void)
{
  puts("Available commands:");
  puts("help - shows this help");
  puts("list - lists all prisoner");
  puts("note - add a note to a prisoner");
  puts("punish - put a prisoner into the bunker");
  return puts("exit - leave");
}

//----- (0000000000001720) ----------------------------------------------------
unsigned __int64 list(void)
{
  Prisoner *prisoner; // rbx
  char *sentence; // rax
  char *risk; // rcx
  char *nickname; // rdx
  char *name; // rsi
  unsigned __int64 i; // [rsp+8h] [rbp-20h]

  prisoner = head;
  for ( i = __readfsqword(0x28u); prisoner; prisoner = prisoner->next )
  {
    sentence = prisoner->sentence;
    risk = prisoner->risk;
    nickname = prisoner->nickname;
    name = prisoner->name;
    if ( !sentence )
      sentence = "";
    if ( !risk )
      risk = "";
    if ( !nickname )
      nickname = "";
    if ( !name )
      name = "";
    printf(
      "Prisoner: %s (%s)\nRisk: %s\nAge: %d\nCell: %d\nSentence: %s\n",
      name,
      nickname,
      risk,
      (unsigned int)prisoner->age,
      (unsigned int)prisoner->cell_number,
      sentence);
    write(1, "Note: ", 6uLL);
    write(1, prisoner->note, (unsigned int)prisoner->note_size);
    puts("\n");
  }
  return __readfsqword(0x28u) ^ i;
}

//----- (0000000000001800) ----------------------------------------------------
unsigned __int64 note(void)
{
  int cell; // eax
  Prisoner *prisoner; // rbx
  unsigned int new_note_size; // ebp
  unsigned int note_size; // eax
  char *new_note; // rax MAPDST
  char buf[8]; // [rsp+0h] [rbp+0h] BYREF
  unsigned __int64 vars8; // [rsp+8h] [rbp+8h]

  vars8 = __readfsqword(0x28u);
  *(_QWORD *)buf = 0LL;
  write(1, "Cell: ", 6uLL);
  read(0, buf, 7uLL);
  cell = strtol(buf, 0LL, 10);
  prisoner = head;
  if ( !head )
    goto abort;
  if ( head->cell_number != cell )
  {
    do
    {
      prisoner = prisoner->next;
      if ( !prisoner )
        goto abort;
    }
    while ( prisoner->cell_number != cell );
  }
  write(1, "Size: ", 6uLL);
  bzero(buf, 8uLL);
  read(0, buf, 7uLL);
  new_note_size = strtol(buf, 0LL, 10);
  note_size = prisoner->note_size;
  if ( note_size < new_note_size && note_size )
  {
    new_note = (char *)realloc(prisoner->note, new_note_size);// implicit free
    prisoner->note = new_note;
    if ( new_note )
      goto asign_note_size;
    goto abort;
  }
  if ( !note_size )
  {
    new_note = (char *)malloc(new_note_size);
    prisoner->note = new_note;
    if ( new_note )
    {
asign_note_size:
      prisoner->note_size = new_note_size;
      goto read;
    }
abort:
    abort();
  }
read:
  write(1, "Note: ", 6uLL);
  secure_read(prisoner->note, new_note_size);
  return __readfsqword(0x28u) ^ vars8;
}

//----- (0000000000001960) ----------------------------------------------------
unsigned __int64 punish(void)
{
  int cell; // eax
  Prisoner *prisoner; // rdi
  char buf[8]; // [rsp+0h] [rbp-18h] BYREF
  unsigned __int64 v4; // [rsp+8h] [rbp-10h]

  v4 = __readfsqword(0x28u);
  if ( occupied )
  {
    write(1, "bunker is occupied\n", 0x13uLL);
  }
  else
  {
    write(1, "Cell: ", 6uLL);
    read(0, buf, 7uLL);
    cell = strtol(buf, 0LL, 10);
    prisoner = head;
    if ( head )
    {
      if ( head->cell_number == cell )
      {
free:
        free(prisoner);                         // just free, nothing else
        occupied = 1;
      }
      else
      {
        while ( 1 )
        {
          prisoner = prisoner->next;
          if ( !prisoner )
            break;
          if ( prisoner->cell_number == cell )
            goto free;
        }
      }
    }
  }
  return __readfsqword(0x28u) ^ v4;
}
// 203028: using guessed type char occupied;
// 1960: using guessed type char buf[8];

//----- (0000000000001A30) ----------------------------------------------------
unsigned __int64 interact(void)
{
  _DWORD *exception; // rax
  _DWORD *v2; // rax
  char command[8]; // [rsp+0h] [rbp-18h] BYREF
  unsigned __int64 v4; // [rsp+8h] [rbp-10h]

  v4 = __readfsqword(0x28u);
  *(_QWORD *)command = 0LL;
  write(1, "> ", 2uLL);
  read(0, command, 7uLL);
  if ( !memcmp(command, "help", 4uLL) )
  {
    help();
  }
  else if ( !memcmp(command, "list", 4uLL) )
  {
    list();
  }
  else if ( !memcmp(command, "note", 4uLL) )
  {
    note();
  }
  else if ( !memcmp(command, "punish", 6uLL) )
  {
    punish();
  }
  else if ( command[0] != '\n' )
  {
    if ( !memcmp(command, "exit", 4uLL) )
    {
      exception = __cxa_allocate_exception(4uLL);
      *exception = 2;
      __cxa_throw(exception, (struct type_info *)&`typeinfo for'int, 0LL);
    }
    v2 = __cxa_allocate_exception(4uLL);
    *v2 = 1;
    __cxa_throw(v2, (struct type_info *)&`typeinfo for'int, 0LL);
  }
  return __readfsqword(0x28u) ^ v4;
}

//----- (0000000000001B80) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v4; // rbx
  signed __int64 v5; // rbp

  v4 = 0LL;
  v5 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v4++])(a1, a2, a3);
    while ( v4 != v5 );
  }
}
// 10F0: using guessed type __int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD);
// 202C88: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 202C90: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000001BF4) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=83 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
